spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN:postgres_user}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:students}
server:
  port: ${SERVER_PORT:8080}

users-service-url: http://${USERS_SERV_URL:localhost:8080/api/users}

